title: Ramp up on Git and GitHub
description: >-
  A set of resources leveraged by Microsoft employees to ramp up on Git and
  GitHub. Progress of this path is intended to take about 4 weeks, including 1
  week of prerequisites.
steps:
  - link: 'https://guides.github.com/introduction/git-handbook/'
    title: Git Handbook
    description: >-
      Week 0 (Prepreqs): This doc on GitHub Guides provides a top-view of Git
      and useful commands.
  - link: 'https://www.youtube.com/watch?v=9S0p8YMQzsM&feature=youtu.be'
    title: GitHub Learning Lab
    description: >-
      Week 0 (Prepreqs): A YouTube video that gives you an overview of Learning
      Lab and how to use it. 
  - course: communicating-using-markdown
    description: >-
      Week 0 (Prepreqs): In this course, youll learn how to: Use Markdown to add
      lists, images, and links in a comment or text file, Determine where and
      how to use Markdown in a GitHub repository
  - link: >-
      https://blog.linkedin.com/2019/september/17/announcing-skill-assessments-to-help-you-showcase-your-skills
    title: 'LinkedIn Skill Assessment: Git'
    description: >-
      Week 0 (Prepreqs): Take the Skill Assessment on Git. This link provides
      Information on how to get started using LinkedIn Assessments.
  - course: introduction-to-github
    description: >-
      Week 1: Outcomes from this lab: Communicate in issues, Manage
      notifications, Create branches, Make commits, Introduce changes with pull
      requests
  - course: 'github-actions:-hello-world'
    description: |-
      Week 1: Outcomes from this lab:

      Organize and identify workflow files, 
      Add executable scripts, 
      Create workflow and action blocks, 
      Trigger workflows, 
      Discover workflow logs, 
  - link: 'https://www.youtube.com/watch?v=E1OunoCyuhY'
    title: GitHub Actions - Now with built-in CI/CD! Live from GitHub HQ
    description: >-
      Week 1: The announcement for the release of GitHub Actions with CI and CD
      capabilities.
  - course: uploading-your-project-to-github
    description: >-
      Week 1: Outcomes from this lab:


      Identify where your code is stored, 

      Introduce code to a repository, 

      Create important Git files like a .gitignore, 

      Identify important next steps to manage your repository and add community
      involvement
  - course: reviewing-pull-requests
    description: |-
      Week 1: Outcomes from this lab:

      Comment on pull requests, 
      Leave reviews on pull requests, 
      See whats expected when reviewing pull requests, 
      Request pull request reviews, 
      Accept changes introduced by a pull request review
  - course: create-a-release-based-workflow
    description: >-
      Week 2: After completing this course, you'll be able to:Build a project
      board to manage your next release, Create & commit changes on a release
      branch, Create a Git tag & a release on GitHub,

      Resolve bugs after a release
  - course: securing-your-workflows
    description: >-
      Week 2: After completing this course, you'll be able to:


      Enable security features,

      Detect vulnerable dependencies in repositories when notified by GitHub's
      security alerts,

      Utilize best practices to keep sensitive data out
  - course: migrating-your-repository-to-github
    description: |-
      Week 2: In this course, youll learn how to:

      Prepare your project for a successful migration,
      Handle any binary files currently stored in your project,
      Create important Git files like a .gitignore
      Import your project to GitHub
  - link: 'https://www.youtube.com/watch?v=8hKkmPuauBE'
    title: 'Git & GitHub: Migrate to GitHub'
    description: 'Week 2: A short video that''ll help you plan a migration to GitHub.'
  - link: 'https://resources.github.com/whitepapers/introduction-to-innersource/'
    title: An introduction to innersource
    description: >-
      Week 3: Organizations worldwide are incorporating open source
      methodologies into the way they build and ship their own software.
  - course: innersource-fundamentals
    description: >-
      Week 3: After completing this course, you'll be able to:contrast user
      versus organization owned repos,

      make recommendations about the number of GitHub orgs you should have,

      create discoverable repositories,

      create robust repository READMEs

      use 
  - link: 'https://gist.github.com/githubteacher/9fe53687a5f173d1d64c24c68625349e'
    title: Case studies for InnerSource
    description: 'Week 3: A set of InnerSource case studies.'
  - link: 'https://gist.github.com/githubteacher/3055abd3344c7947881f118d02279949'
    title: Picking InnerSource projects
    description: >-
      Week 3: Information to help you pick how to pick a project for InnerSource
      practices.
  - link: 'https://gist.github.com/githubteacher/751d3759431ea03af93cf04957731dd1'
    title: Checks for understanding
    description: Check your understanding by trying some of these questions.
